### ISSUE TITLE
Possibly replace gen palkha video with new brigade promo video

### ISSUE THREAD

**Issue by qwo** [Code4HR/code4hr#12]
its shorter and geared toward brigade what do people think?

https://twitter.com/StanZheng/status/542615205260570624

**Comment by kmcurry** [comment]
:+1:

**Comment by kmcurry** [comment]
:+1:

On Wed, Dec 10, 2014 at 7:12 PM, Stanley Zheng notifications@github.com
wrote:

> its shorter and geared toward brigade
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Code4HR/code4hr/issues/12.

## 

Kevin Curry
Virginia Beach, VA

3Scape begins @ http://3Scape.me

**Comment by qwo** [comment]
this is the actual video, confused it for a tweet doh
https://www.youtube.com/watch?v=PinRhW8Psn4
