### ISSUE TITLE
Add Code4HR Slack to social media menu bar

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/code4hr#14]
![screen shot 2014-12-10 at 9 38 52 pm](https://cloud.githubusercontent.com/assets/69151/5388215/07065356-80b5-11e4-98b1-d3a7b3f85b65.png)

**Comment by BretFisher** [comment]
chat.code4hr.org (the chat bubbles link) now points to http://code4hrslacksignup.meteor.com/
