### ISSUE TITLE
Add a page that lists issues we need help on

### ISSUE THREAD

**Issue by wbprice** [Code4HR/code4hr#31]
Use the GitHub API to fetch issues with a "Help Wanted" tag and list them on a page.

**Comment by kmcurry** [comment]
That's not what the Brigade API is for?

**Comment by qwo** [comment]
The brigade API filtering is on the main home page at code4hr.org. I think when I replaced it after the URL fixed it removed the `help-wanted` tag.

**Comment by qwo** [comment]
It looks like I forgot to put the `help wanted` tag in the query parameter here; 

added it here, should be propogated soon.

https://github.com/Code4HR/code4hr/commit/a70a6ea84c931c13ec7f8752ddb765419e7f8538

**Comment by qwo** [comment]
this is the default route

http://civicissues.codeforamerica.org/geeks/civicissues/widget?organization_name=Code-for-Hampton-Roads&number=5&issue=help

**Comment by qwo** [comment]
so actually that was a coincidence, it looks like it doesn't recognize the parameter ill double check this.

**Comment by qwo** [comment]
ok so instead of `issue` its `labels` in the civic issue finder vs the brigade api .. 

https://github.com/codeforamerica/civic-issue-finder

**Comment by qwo** [comment]
@wbprice let me know if this is now closed.

**Comment by kmcurry** [comment]
The section on our page is working so I'm calling it closed.
