### ISSUE TITLE
Missing favicon in browser tab

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/code4hr#32]
![screen shot 2017-02-16 at 11 22 54 pm](https://cloud.githubusercontent.com/assets/69151/23052407/f6341b5c-f49e-11e6-9a39-610301d65c45.png)

**Comment by kmcurry** [comment]
🤘

**Comment by bcbarsness** [comment]
The PR was a bit overkill but allowed me to brush up on the workflow.
